# Generated by Django 2.2.1 on 2019-06-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contract', models.CharField(max_length=10, verbose_name='Номер контракта')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(0, 'Не выполнен'), (1, 'Выполняется'), (2, 'Выполнен')], verbose_name='Статус')),
                ('link_file', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на файл')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=12, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300, verbose_name='Название проекта')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата конца')),
                ('id_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Contract', verbose_name='Номер контракта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=200, verbose_name='Название вида задачи')),
            ],
            options={
                'verbose_name': 'Вид задачи',
                'verbose_name_plural': 'Виды задач',
            },
        ),
        migrations.CreateModel(
            name='Type_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_customer', models.CharField(max_length=100, verbose_name='Тип заказчика')),
            ],
            options={
                'verbose_name': 'Тип заказчика',
                'verbose_name_plural': 'Типы заказчика',
            },
        ),
        migrations.CreateModel(
            name='Type_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=150, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы проектов',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_photo', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на фото')),
                ('surname', models.CharField(blank=True, max_length=80, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('experience', models.IntegerField(blank=True, verbose_name='Опыт работы')),
                ('gender', models.CharField(blank=True, max_length=3, verbose_name='Пол')),
                ('date_birth', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Номер телефона')),
                ('mail', models.CharField(blank=True, max_length=40, verbose_name='Email')),
                ('id_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Project_participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Не выполнена'), (1, 'Выполняется'), (2, 'Выполнена')], verbose_name='Статус')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project', verbose_name='Проект')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Участие',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Type_project', verbose_name='Тип проекта'),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=300, verbose_name='Название задачи')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('date_start_plan', models.DateField(verbose_name='Дата конца по плану')),
                ('date_end_plan', models.DateField(verbose_name='Дата начала по плану')),
                ('date_start_actual', models.DateField(null=True, verbose_name='Дата фактического начала')),
                ('date_end_actual', models.DateField(null=True, verbose_name='Дата фактического конца')),
                ('status', models.IntegerField(choices=[(0, 'Не выполнена'), (1, 'Выполняется'), (2, 'Выполнена')], verbose_name='Статус')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project', verbose_name='Проект')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Task', verbose_name='Вид задачи')),
            ],
            options={
                'verbose_name': 'Задач',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Doer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project_participant', verbose_name='Участие в проекте')),
                ('id_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=150, verbose_name='Заказчик')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=130, verbose_name='Email')),
                ('id_type_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Type_customer', verbose_name='Тип заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Customer', verbose_name='Заказчик'),
        ),
    ]
