# Generated by Django 2.2.1 on 2019-06-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.CharField(max_length=200, verbose_name='Заказчик'),
        ),
    ]
