# Generated by Django 2.2.1 on 2019-06-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20190612_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mail',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='mail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='patronymic',
            field=models.CharField(blank=True, max_length=55, verbose_name='Отчество'),
        ),
    ]
