# Generated by Django 2.2.1 on 2019-06-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_auto_20190612_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='date_end_actual',
            field=models.DateField(blank=True, null=True, verbose_name='Дата фактического конца'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='date_start_actual',
            field=models.DateField(blank=True, null=True, verbose_name='Дата фактического начала'),
        ),
    ]
